CREATE DATABASE log;
USE log;
DROP TABLE IF EXISTS IP_LOG;

CREATE TABLE IP_LOG(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REQUEST_DATE timestamp NOT NULL,
    IP VARCHAR(15) NOT NULL,
    REQUEST VARCHAR(20) NOT NULL,
    STATUS INTEGER NOT NULL,
    AGENT VARCHAR(500) NOT NULL
);



DROP TABLE IF EXISTS BLOCKED_IP;

CREATE TABLE BLOCKED_IP (
	IP VARCHAR(15) PRIMARY KEY NOT NULL,
    FREQUENCY INTEGER NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL
);
